global using System.Net;
global using BusinessLogic.Interfaces;
global using Domain.Entities;
global using DataAccessLayer.Interfaces;
global using Microsoft.AspNetCore.Http;
global using Domain.ViewModels;
global using Domain.DTO;
global using Microsoft.EntityFrameworkCore;
global using Domain.DTO;